#Deployment
###controllers/loyalty-deploy.tml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customerbroker-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: customerbroker-app
  template:
    metadata:
      labels:
        app: customerbroker-app
    spec:
      containers:
      - name: customerbroker-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: customerbroker-config
      imagePullSecrets:
      - name: loyalsecret

