#Deployment
###controllers/pb-deploy.tml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pb-app
  template:
    metadata:
      labels:
        app: pb-app
    spec:
      containers:
      - name: pb-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: prb-config
        volumeMounts:
        - name: nfs-volume
          mountPath: "/data"
        - name: nfs-volume1
          mountPath: "/opt/history"
        - name: efklog
          mountPath: /var/log
      - name: count-log-1
        image: busybox
        args: [/bin/sh, -c, 'tail -n+1 -F /var/log/pb.log']
        volumeMounts:
        - name: efklog
          mountPath: /var/log  
      volumes:
      - name: nfs-volume
        nfs:
          server: 153.78.37.157
          path: /data
      - name: nfs-volume1
        nfs:
          server: 153.78.37.157
          path: /opt/
          - name: efklog
        emptyDir: {}
      imagePullSecrets:
      - name: loyalsecret


