# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: pb-demo
  labels:
    app: pp-app
spec:
  selector:
    app: pb-app
  type: LoadBalancer
  ports:
  - nodePort: 32750
    port: 8080
    targetPort: 8080

